USE exam_room_allocation_system;
CREATE TABLE IF NOT EXISTS ADMIN_USERS (
    ADMIN_ID INT PRIMARY KEY AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Password is: admin123
INSERT INTO ADMIN_USERS(FULL_NAME,USERNAME,PASSWORD_HASH)
SELECT 'System Administrator','admin','$2y$12$cM5tq6hohRa.bOl8HvYhtOY/6frzwdh.7YzxtkGGkbneZRRy723yW'
WHERE NOT EXISTS (SELECT 1 FROM ADMIN_USERS WHERE USERNAME='admin');
